### PR TITLE
fix for new version of pg

### PR DESCRIPTION
**Pull request by contra**
The last minor release broke this module, this PR should fix it.

### CODE REVIEW

**Comment by brianc** [comment]
Thanks for putting this together!  Can you bump the version in `package.json` to `pg: '7.x'`?  That way the tests will pass.  Thanks!

**Comment by contra** [comment]
@brianc Updated the deps in package.json. As an aside - the tests fail on latest node versions, and travis is using some pretty old stuff. Core stream behavior has changed since node 8 so something will probably need to be updated in a major breaking release + dropping support for older versions of node.

**Comment by brianc** [comment]
oof tests are failing on every version of node.  I'll update to newer versions of node & figure out why they're failing.  Probably wont be able to get to this until tomorrow or thursday

**Comment by contra** [comment]
@brianc Let me know if you want me to look into it + update the travis config as a part of this PR.

**Comment by brianc** [comment]
Closed with #57

**Comment by contra** [comment]
@brianc Can you publish the changes?

**Comment by brianc** [comment]
yup will do today!

**Pull request closed without merging**
