### PR TITLE
Return result accumulator in callback

### PR DESCRIPTION
**Pull request by sberan**
see issue: https://github.com/brianc/node-pg-cursor/issues/22

### CODE REVIEW

**Comment by brianc** [comment]
Beautiful! 💃

**Comment by brianc** [comment]
pusing a new minor version to npm in just a few min.

**Comment by sberan** [comment]
thanks! ⚡️

**Comment by brianc** [comment]
Published `pg-cursor@1.1.0`!! 💃

**Comment by sberan** [comment]
💯  Much appreciated!

**Pull request merged**
