### PR TITLE
Fix require for webpack compatibility

### PR DESCRIPTION
**Pull request by crisvergara**
Small change that might only impact me. I use webpack to package server-side stuff. It doesn't play well with require.resolve. This code accomplishes the same thing and plays nice with webpack.

### CODE REVIEW

**Comment by brianc** [comment]
Thanks for your help @crisvergara! I'm really sorry it took me so long to get to this. 😢 

I'll push out a new patch version right now!!

**Comment by crisvergara** [comment]
@dpnova Just specify pg.js as external in your webpack config: https://webpack.js.org/configuration/externals/

**Comment by dpnova** [comment]
thanks @crisvergara - will try this out

**Comment by crisvergara** [comment]
I updated my own project to Webpack 3 recently. I had to add the following externals:
`['pg.js/lib/result.js', 'pg.js/lib/utils.js']`

**Pull request merged**
